install.packages('dartRverse')
install.packages('BiocManager')
BiocManager::install('SNPRelate')
BiocManager::install('snpStats')
install.packages('sf')
install.packages('leaflet')
install.packages("pak")
pak::pak("terra@1.7-83") 
pak::pak("raster@3.6-30")
#### DO NOT UPDATE PACKAGES raster or terra
library(dartRverse)
dartRverse_install('dartR.base', rep='Github', branch='dev')
dartRverse_install('dartR.popgen', rep='Github', branch='dev')
dartRverse_install('dartR.captive', rep='Github', branch='dev')
dartRverse_install('dartR.sim', rep='Github', branch='dev')
dartRverse_install('dartR.spatial', rep='Github', branch='dev')
dartRverse_install('dartR.sexlinked', rep='Github', branch='dev')
